export const serviceCategories = [
  {
    id: 'energy-sustainability', number: '01', title: 'Energy & Sustainability',
    description: 'Energy assessments and implementation support designed to reduce consumption, operating cost and environmental impact.',
    href: 'services/audits-sustainability', image: 'assets/images/home/hero-audit.webp', imageWidth: 1536, imageHeight: 1024,
    imageAlt: 'Engineer inspecting industrial equipment during an energy assessment',
    services: [
      ['Energy Audit', 'services/energy-audits'],
      ['Comprehensive Energy Audit', 'services/comprehensive-energy-audit'],
      ['Compressed Air Leakage Testing', 'services/compressed-air-testing'],
      ['Steam System Analysis', 'services/steam-analysis'],
      ['Boiler Efficiency Testing', 'services/boiler-efficiency'],
      ['Energy Saving Projects', 'services/energy-saving-projects'],
      ['Execution of Recommendations', 'services/execution-recommendations'],
      ['Carbon Footprint Analysis', 'services/carbon-footprint'],
      ['Renewable Energy', 'services/renewable-energy'],
      ['Water Audit', 'services/water-audit'],
    ],
  },
  {
    id: 'electrical-safety', number: '02', title: 'Electrical Safety & Power Systems',
    description: 'Electrical risk assessment, power-system analysis and protection studies for safer and more reliable facilities.',
    href: 'services/electrical-safety-audit', image: 'assets/images/home/Thermography.webp', imageWidth: 1600, imageHeight: 765,
    imageAlt: 'Thermographic inspection of industrial electrical equipment',
    services: [
      ['Electrical Safety Audits', 'services/electrical-safety-audit'],
      ['Power Quality Analysis', 'services/power-quality-analysis'],
      ['Electrical Thermography', 'services/electrical-thermography'],
      ['Arc Flash Study', 'services/arc-flash-study'],
      ['E-Hazop', 'services/e-hazop'],
      ['Lightning Protection System', 'services/lightning-protection'],
    ],
  },
  {
    id: 'health-safety-environment', number: '03', title: 'Health, Safety & Environment',
    description: 'Workplace health, behavioural safety, process-risk and employee well-being programmes for industrial organisations.',
    href: 'services/hira', image: 'assets/images/home/hero-audit-1180.webp', imageWidth: 1180, imageHeight: 787,
    imageAlt: 'Safety-trained engineer carrying out an industrial site inspection',
    services: [
      ['Occupational Health Risk Assessment', 'services/occupational-health'],
      ['Ergonomics Assessment', 'services/ergonomics'],
      ['First-aid & Medical Facilities', 'services/first-aid-facilities'],
      ['Hazard Identification & Risk Assessment', 'services/hira'],
      ['Permit-to-work Systems', 'services/permit-to-work'],
      ['Behavioural Based Safety Audit', 'services/behavioural-safety'],
      ['Incident / Near-Miss Reporting Systems', 'services/incident-reporting'],
      ['Process Safety', 'services/process-safety'],
      ['Tool Box Talks', 'services/tbt'],
      ['Well-Being Audit', 'services/well-being-audit'],
      ['POSH Training', 'services/posh-training'],
    ],
  },
  {
    id: 'fire-safety', number: '04', title: 'Fire Safety & Fire Protection',
    description: 'Fire-risk assessment, emergency planning, detection, suppression and complete fire-protection execution.',
    href: 'services/fire-life-safety', image: 'assets/images/fire-safety.webp', imageWidth: 275, imageHeight: 183,
    imageAlt: 'Industrial fire-protection and emergency response equipment',
    services: [
      ['Fire & Life Safety Audits', 'services/fire-life-safety'],
      ['Fire Load Study', 'services/fire-load-study'],
      ['Fire Pump Performance Testing', 'services/fire-compliance'],
      ['Disaster Management Plans', 'services/disaster-management'],
      ['Emergency Preparedness Plans', 'services/emergency-preparedness'],
      ['Compliance & Safety System', 'services/fire-compliance'],
      ['Drills & Simulation Exercises', 'services/drills-simulation'],
      ['Turnkey Fire Fighting Projects', 'services/fire-projects'],
      ['Fire Detection System', 'services/fire-detection'],
      ['Portable & Fixed Fire Extinguishers', 'services/fire-extinguishers'],
      ['Fire Door Installation', 'services/fire-doors'],
      ['Public Addressable System', 'services/public-address'],
      ['FM-200 & Kitchen Suppression', 'services/fm200'],
      ['VESDA Projects', 'services/fire-detection'],
    ],
  },
  {
    id: 'compliance-approvals', number: '05', title: 'Compliance, Certification & Approvals',
    description: 'Technical documentation, certification and approval support for statutory and regulatory requirements.',
    href: 'services/compliances', image: 'assets/images/home/compliance.webp', imageWidth: 1536, imageHeight: 1024,
    imageAlt: 'Engineering compliance documentation prepared for statutory review',
    services: [
      ['Environment Compliances', 'services/environment-compliances'],
      ['NOC – Electrical Compliance', 'services/electrical-compliance'],
      ['Lift NOC & Approvals', 'services/lift-noc'],
      ['Fire NOC & Approvals', 'services/fire-noc'],
      ['MCD NOC & Approvals', 'services/mcd-noc'],
      ['Chartered Engineering', 'services/chartered-engineering'],
    ],
  },
  {
    id: 'hvac-iaq', number: '06', title: 'HVAC & Indoor Air Quality',
    description: 'HVAC, ventilation and indoor-air-quality solutions from design through commissioning and performance improvement.',
    href: 'services/hvac-projects', image: 'assets/images/home/hvac-project.webp', imageWidth: 1536, imageHeight: 1024,
    imageAlt: 'Industrial HVAC and ventilation system installed at a facility',
    services: [
      ['Turnkey HVAC Projects', 'services/hvac-projects'],
      ['Design to Execution – VRF, VRV and Chillers', 'services/hvac-design'],
      ['Installation & Commissioning', 'services/hvac-installation'],
      ['Turnkey Ventilation Projects', 'services/ventilation-projects'],
      ['Robo Duct Cleaning', 'services/duct-cleaning'],
      ['Air Balancing & Indoor Air Quality', 'services/air-balancing'],
    ],
  },
  {
    id: 'emission-control', number: '07', title: 'Emission Control & Environmental Monitoring',
    description: 'Emission-control systems, environmental testing and waste-management solutions for regulatory compliance.',
    href: 'services/emission-control', image: 'assets/images/home/emission-project.webp', imageWidth: 1535, imageHeight: 1025,
    imageAlt: 'Industrial emission-control equipment and monitored exhaust stack',
    services: [
      ['RECD & DFK Kit', 'services/recd-kit'],
      ['OCEMS Projects', 'services/ocems'],
      ['New CPCB 4+ DGs', 'services/cpcb-dgs'],
      ['New CPCB 4+ Gas DG', 'services/gas-dg'],
      ['Stack Emission Test', 'services/stack-emission'],
      ['NABL Testing & Noise Monitoring', 'services/nabl-testing'],
      ['Duct/Stack Cleaning', 'services/stack-cleaning'],
      ['Waste Management', 'services/waste-management'],
      ['E-waste Solutions', 'services/e-waste-solutions'],
    ],
  },
  {
    id: 'electrical-infrastructure', number: '08', title: 'Electrical Engineering & Infrastructure',
    description: 'Complete electrical infrastructure, distribution, earthing, solar and EV-charging project execution.',
    href: 'services/electrical-projects', image: 'assets/images/home/lighting.webp', imageWidth: 1128, imageHeight: 1300,
    imageAlt: 'Completed industrial electrical and lighting infrastructure',
    services: [
      ['Turnkey Electrical Projects', 'services/electrical-projects'],
      ['Sales & Services – HT, LT and Panels', 'services/electrical-sales'],
      ['Transformer Dehydration', 'services/transformer-dehydration'],
      ['Earthing Projects', 'services/earthing-projects'],
      ['Distribution Panel Projects', 'services/panel-projects'],
      ['Cable Laying & Termination', 'services/cable-laying'],
      ['Cable Tray Installations', 'services/cable-tray'],
      ['Solar Systems Projects', 'services/solar-projects'],
      ['EV Charging Stations', 'services/ev-charging'],
    ],
  },
  {
    id: 'lighting-automation', number: '09', title: 'Lighting, Automation & Smart Infrastructure',
    description: 'Commercial, industrial and outdoor lighting systems with automation and smart-control capabilities.',
    href: 'services/lighting-projects', image: 'assets/images/home/lighting.webp', imageWidth: 1128, imageHeight: 1300,
    imageAlt: 'Energy-efficient lighting installed in an industrial facility',
    services: [
      ['Office Lights – Suspended, Downlighters and Spot Lights', 'services/office-lighting'],
      ['Smart LED Batten & Customised Lights', 'services/smart-lighting'],
      ['Industrial Lights – High Bays and Canopy Lights', 'services/industrial-lighting'],
      ['Street Lights, Flood Lights and Bollards', 'services/outdoor-lighting'],
      ['Wall Mount, Step-Light and Post-Top Fixtures', 'services/wall-mount-lighting'],
      ['Solar-Based LED Systems', 'services/solar-lighting'],
      ['All Kinds of Poles & Designer Lights', 'services/poles-designer-lights'],
      ['Lighting & Automation Projects', 'services/lighting-projects'],
    ],
  },
  {
    id: 'project-execution', number: '10', title: 'Engineering, Construction & Project Execution',
    description: 'Project coordination, maintenance and construction support for industrial and commercial facilities.',
    href: 'services/project-management', image: 'assets/images/home/hvac-project.webp', imageWidth: 1536, imageHeight: 1024,
    imageAlt: 'Engineering project execution at an industrial facility',
    services: [
      ['Project Management', 'services/project-management'],
      ['Repair & Maintenance', 'services/repair-maintenance'],
      ['Interior Design Projects', 'services/interior-design'],
    ],
  },
  {
    id: 'risk-consulting', number: '11', title: 'Risk Management & Specialised Consulting',
    description: 'Specialised cyber, operational and insurance-risk consulting for organisations and critical infrastructure.',
    href: 'services/risk-management', image: 'assets/images/home/compliance.webp', imageWidth: 1536, imageHeight: 1024,
    imageAlt: 'Technical risk and control review for an industrial organisation',
    services: [
      ['Cyber Audits', 'services/cyber-audits'],
      ['Risk Management & Insurance Planning', 'services/risk-management'],
    ],
  },
].map((category) => ({
  ...category,
  services: category.services.map(([title, href]) => ({ title, href, slug: href.split('/').pop() })),
}));

export default serviceCategories;
