name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 118.139.182.215
          username: deploy@b2bindustrial.in
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
